### ISSUE TITLE
System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by billlin0904** [StormHub/NetUV#36]
Dear ~

I got the exception IndexOutOfRangeException when received data, In my code only receive no send any data.

So, how to fix the problem?

System.IndexOutOfRangeException: index:0, length:256 expected range >= 0 and < 0.
   於 NetUV.Core.Buffers.ByteBuffer.Validate(Int32 index, Int32 length)
   於 NetUV.Core.Buffers.ReadableBuffer.ReadString(Int32 length, Encoding encoding)

**Comment by StormHub** [comment]
Hi, 
Could you please give a bit more details about the stack trace? is it udp or  tcp? 
Aslo, which version it is? I fixed some issue like this a while back.

**Comment by billlin0904** [comment]
I am using TCP socket in the project. logging as follows...

static void OnAccept(StreamHandle stream, ReadableBuffer data)
        {
            try
            {
                string message = data.Count > 0 ? data.ReadString(data.Count, Encoding.UTF8) : null;
                if (string.IsNullOrEmpty(message))
                {
                    return;
                }

                Console.WriteLine(message);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            finally
            {
                data.Dispose();
            }
        }


dbug: ReceiveBufferSizeEstimate[0]
      ReceiveBufferSizeEstimate allocate, estimated size = 496
trce: Pipeline[0]
      Pipeline receive buffer allocated size = 512
dbug: ScheduleHandle[0]
      UV_TCP 94530136 read, buffer length = 512 status = 49.
dbug: ReceiveBufferSizeEstimate[0]
      ReceiveBufferSizeEstimate record actual size = 49, next size = 496
dbug: ReceiveBufferSizeEstimate[0]
      ReceiveBufferSizeEstimate allocate, estimated size = 496
trce: Pipeline[0]
      Pipeline receive buffer allocated size = 512
dbug: ScheduleHandle[0]
      UV_TCP 94530136 read, buffer length = 512 status = 74.
dbug: ReceiveBufferSizeEstimate[0]
      ReceiveBufferSizeEstimate record actual size = 74, next size = 480
dbug: ReceiveBufferSizeEstimate[0]
      ReceiveBufferSizeEstimate allocate, estimated size = 480
trce: Pipeline[0]
      Pipeline receive buffer allocated size = 512
dbug: ScheduleHandle[0]
      UV_TCP 94530136 read, buffer length = 512 status = 74.
dbug: ReceiveBufferSizeEstimate[0]
      ReceiveBufferSizeEstimate record actual size = 74, next size = 480
dbug: ReceiveBufferSizeEstimate[0]
      ReceiveBufferSizeEstimate allocate, estimated size = 480
trce: Pipeline[0]
      Pipeline receive buffer allocated size = 512
dbug: ScheduleHandle[0]
      UV_TCP 94530136 read, buffer length = 512 status = 26.
dbug: ReceiveBufferSizeEstimate[0]
      ReceiveBufferSizeEstimate record actual size = 26, next size = 464
dbug: ReceiveBufferSizeEstimate[0]
      ReceiveBufferSizeEstimate allocate, estimated size = 464
trce: Pipeline[0]
      Pipeline receive buffer allocated size = 512
dbug: ScheduleHandle[0]
      UV_TCP 94530136 read, buffer length = 512 status = 512.
dbug: ReceiveBufferSizeEstimate[0]
      ReceiveBufferSizeEstimate record actual size = 512, next size = 1024
System.IndexOutOfRangeException: index:0, length:512 expected range >= 0 and < 0.
   於 NetUV.Core.Buffers.ByteBuffer.Validate(Int32 index, Int32 length)
   於 NetUV.Core.Buffers.ReadableBuffer.ReadString(Int32 length, Encoding encoding)
   於 EventLoopTest.Program.OnAccept(StreamHandle stream, ReadableBuffer data) 於 C:\Users\billl\documents\visual studio 2015\Projects\EventLoopTest\EventLoopTest\Program.cs: 行 41

**Comment by StormHub** [comment]
I have found the issue, buffer validation should be based on buffer capacity rather than the inner length.
Thanks for reporting the issue.

**Comment by StormHub** [comment]
PR fix Merged.
