### ISSUE TITLE
May you support old target framework? .Net Framework 4.5.2

### ISSUE THREAD

**Issue by billlin0904** [StormHub/NetUV#38]
To encounter framework issue
Hi Johnny, I try to apply NetUV in my code(.Net Framework4.5.2), but have some problem about .netframework
, may you thinking to support.Net Framework4.52, thank you.

**Comment by StormHub** [comment]
I think I could target 452, the reason I switched to 461 was because of some dependency packages require 46. Please let me have a look at this first. Thanks.

**Comment by StormHub** [comment]
Just let you know that if your project target .NET Stand 1.3, it would work.

**Comment by StormHub** [comment]
System.Net.NameResolution 4.3.0 is not compatible with net45 
supports: net46 (.NETFramework,Version=v4.6)
That was the reason I bumped up to 4.6

**Comment by StormHub** [comment]
Other Microsoft extensions all supports 4.51, looks fine.

**Comment by StormHub** [comment]
Closing this issue for now.
