### ISSUE TITLE
Support reading a string from a buffer till a delimiter from ReadableBuffer

### ISSUE THREAD

**Issue by seertenedos** [StormHub/NetUV#39]
I am working on a Nntp server/client that uses a /r/n command delimiter but really it could be any delimiter people want instead of a fixed string length. since you are wrapping a socket lib the chances are people will want it for some sort of protocol so some way to check the location of something in the buffer and to extract to that point would be great. I don't really want to manage a string buffer on top of our ReadableBuffer as it seems like a waste to double buffer.

**Comment by StormHub** [comment]
The internal buffer actually had this built in but not exposed. Let me have a look at it first.

**Comment by seertenedos** [comment]
Thanks.

**Comment by StormHub** [comment]
Initially, the idea was to pull the entire buffer as a string and decrements the buffer ref.

**Comment by seertenedos** [comment]
In my case I am basically a pass though between multi client to multi
server so want to minimise work I do. If I read out 1.5 commands then I
need to store the 0.5 of a command till the rest comes in.

Even thought about reading pure binary but still have a similar issue of
needing to read till a particular character or byte code so need to buffer
the extra data for the complete next command.

**Comment by StormHub** [comment]
I see.

**Comment by seertenedos** [comment]
basically i am aiming for over 80mbps thoughput. i could only get 80mbps using standard dotnet core sockets so i am hoping libuv and more efficient handling of the network level will help with performance

**Comment by StormHub** [comment]
I put libuv and netty buffer management together is pretty much aiming to achieve the same thing, very tight io spin with zero buffer copy :D

**Comment by seertenedos** [comment]
i could see that it seemed well done so that was why i was hoping it could be built into the buffer if possible.

**Comment by StormHub** [comment]
let me expose some sort of read until to the buffer.

**Comment by seertenedos** [comment]
just wanted to let you know converted my code over to your lib from normal coreclr TcpClient using async without converting my clients yet and instantly halved cpu usage and got 110mbps thoughput which is the max of my internet connection. great job on performance! The buffer request above will most likely help even further and i can't wait to see cpu usage once i convert my client code as well.

**Comment by StormHub** [comment]
Glad to hear! One of my motivations of this package was almost the same as what you have seen. Win sock async api does lots of context switching and buffer copying. I could not afford that for some heavy network tunnelling applications.

**Comment by StormHub** [comment]
PR merged.
