### ISSUE TITLE
Cause NullReferenceException in EventLoop

### ISSUE THREAD

**Issue by Norgerman** [StormHub/NetUV#47]
`RunLoop` is called later than `Schedule`(sometimes maybe), and then will cause a ` NullReferenceException`

**Comment by Norgerman** [comment]
pr #46

**Comment by StormHub** [comment]
Hi, do you have full stack trace for this?

**Comment by StormHub** [comment]
I believe it might be a better option to just do the schedule, then wait for the loop to start and process.
e.g. wait for the loop in a run state where it is guaranteed not to be null.

**Comment by StormHub** [comment]
Let me change it a bit and let you to have a look at it.

**Comment by Norgerman** [comment]
the error's stack trace，just use the loopthread sample
```
Loop thread error System.NullReferenceException: Object reference not set to an instance of an object.
   at NetUV.Core.Channels.EventLoop.Schedule(Action`1 action) in C:\Users\XXX\Desktop\NetUV\src\NetUV.Core\Channels\EventLoop.cs:line 94
   at LoopThread.Program.Main(String[] args) in C:\Users\XXX\Desktop\NetUV\examples\LoopThread\Program.cs:line 31.
```

**Comment by StormHub** [comment]
I see, thanks.

**Comment by StormHub** [comment]
Well, the intention is that
await RunLoopAsync();
then call
eventLoop.Schedule

I will fix the example.

**Comment by Norgerman** [comment]
In the code show that  `await RunLoopAsync();` will block util the loop is closed，so `eventLoop.Schedule` will not be called property....

**Comment by StormHub** [comment]
There are a few places need to be guarded properly. Let me change it first.

**Comment by StormHub** [comment]
The EventLoop class is kind of experimental, forget to put some attribute on it.

**Comment by Norgerman** [comment]
:smile:

**Comment by StormHub** [comment]
#48, try it out.

**Comment by Norgerman** [comment]
works~ 👍

**Comment by StormHub** [comment]
PR #48
