### ISSUE TITLE
Question about ReadableBuffer.ReadString with separator

### ISSUE THREAD

**Issue by oliverw** [StormHub/NetUV#49]
Hi Jonny

I've recently replaced my own implementation of a managed wrapper around LibUv with NetUV and got a question about the <code>ReadableBuffer.ReadString</code> overload that accepts a separator. I'm using this to split incoming character data into lines:

https://github.com/coinfoundry/mining-core/blob/master/src/MiningCore/JsonRpc/JsonRpcConnection.cs#L46

What I'm not sure about (without digging deeper into NetUv) is what happens if ReadString is called when a newline has not yet been received (meaning client is somehow sending data in chunks).

**Comment by StormHub** [comment]
If the separator is not found, then entire content will be read out as string.

**Comment by oliverw** [comment]
Thanks. I need to change my implementation then.
