### ISSUE TITLE
Multiple loops and threads

### ISSUE THREAD

**Issue by Green7** [StormHub/NetUV#55]
I'm trying to run multiple loops (Loop class) in separate threads.
Its works but I have problems on application shutdown.

So it is possible to run two (or more) loops in separate threads (or tasks) ?
Any tips on how to do this properly ?

**Comment by StormHub** [comment]
The loop is designed to run in a single thread and you can use as many loops as you like as long as the handles bound to the loop are executed properly from the loop they are created.
I am not sure about what you mean by problems on shutdown, what was the issue?

**Comment by Green7** [comment]
This is the situation:
I have a listening thread. It looks like:
```
new Thread(
        () =>
          {
            _loop = new Loop();
            IDisposable handle = null;
            handle = _loop
              .CreateTcp()
              .SimultaneousAccepts(true)
              .Listen(new IPEndPoint(IPAddress.Parse("127.0.0.1"), 1234), OnConnected);
            _loop.RunDefault();
            handle.Dispose();
          }).Start();

```

To stop this thread I call: `_loop?.Dispose(); ` from main thread. Everything works fine, I can connect, (from other aplication) send data, and stop the thread without problems.

Now I'm creating second thread. The second thread does not listen but connects to the first one. 
The second thread code looks the same, the only difference is: 
```
             handle = _loop
              .CreateTcp()
              .ConnectTo(new IPEndPoint(IPAddress.Any, IPEndPoint.MinPort), new IPEndPoint(IPAddress.Parse("127.0.0.1"), 1234), OnConnected);
```
After run these two threads I'm stop them as before by loops Dispose(); But it causes exception:

```
$exception	{System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'BufferQueue'.
   at NetUV.Core.Native.BufferQueue.CheckDisposed()
   at NetUV.Core.Handles.Pipeline.AllocateReadBuffer()
   at NetUV.Core.Handles.StreamHandle.OnAllocateCallback(IntPtr handle, IntPtr suggestedSize, uv_buf_t& buf)
   at NetUV.Core.Native.NativeMethods.uv_run(IntPtr handle, uv_run_mode mode)
   at NetUV.Core.Handles.LoopContext.Run(uv_run_mode mode)
   at NetUvTest.Client.<Start>b__3_0() in P:\Tarnina\_Other_\NetUvTest\NetUvTest\Client.cs:line 31
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)}	System.ObjectDisposedException

```
This exception always occurs in a **thread that is stopped last**. So it looks like threads have some common object.

I have tried other methods to stop the threads but without success. Maybe I should use signal or event to stop threads and call dispose not from main thread but from thread that created loop ?

**Comment by StormHub** [comment]
If you run both loops in the same app domain, the only things stream handles share is the buffer allocator which is thread safe. From the stack trace, it looks like the handle is still preparing to receive data.  Are you sure the server handles are inactive?  One more thing, it is better to close the loop with clients first before closing down the server.

**Comment by Green7** [comment]
In my test application I do not send any data.  ConnectedAction handler is empty but exception is raised.
I tried call streamHandle.CloseHandle() (from main thread) before _loop?.Dispose() - without succes, exception still exists.

**Comment by StormHub** [comment]
Let me test this first and get back to you

**Comment by StormHub** [comment]
One more thing you can do though is that call stream handle shutdown first before disposing the loop. 
https://github.com/StormHub/NetUV/blob/c310cffa0b2735c80b19c6a8ad43e915d57c0d6f/test/NetUV.Core.Tests.Performance/TcpWriteBatch.cs#L72
That would stop handles from allocating memory.

**Comment by Green7** [comment]
If I do:
tcp.Shutdown(this.OnShutdown);  or simply tcp.CloseHandle() from  OnConnected/ OnAccept methods (as it is in TcpWriteBatch.cs) everything looks ok.

But I want to shutown from other thread, so I tried to call tcp.Shutdown(this.OnShutdown) from main thread but it does not work - OnShutdown event is not called (why ?).

**Comment by StormHub** [comment]
Libuv requires all handle methods to be called in the same thread. As far as I know of, only async handle supports being called from another thread.

**Comment by Green7** [comment]
So, how to close for example server from other thread ?  Do you have a solution for this ?  Maybe is possible to send signal to server thread and close it from their thread ?

**Comment by StormHub** [comment]
One way of doing it is to use async handle, similar to the EventLoop. 
https://github.com/StormHub/NetUV/blob/dev/src/NetUV.Core/Channels/EventLoop.cs
