### ISSUE TITLE
When to Dispose Async

### ISSUE THREAD

**Issue by oliverw** [StormHub/NetUV#56]
Is it valid to Dispose an Async Handle within its callback like this?:

```csharp
var disposer = loop.CreateAsync((handle) =>
{
    tcp.Dispose();

    handle.Dispose();
});
```

The purpose of this example is to schedule the disposal of another loop-bound resource on the loop  thread.

**Comment by StormHub** [comment]
Yes it is, normal once off running for async handle. 
There are some cases where you need to worry about closure, I typically do something like this:

            asyncHandle = this.loop.CreateAsync(
                handle =>
                {
                    var disposible = handle.UserToken as IDisposable;
                    disposible?.Dispose();
                    handle.Dispose();
                });
            asyncHandle.UserToken = tcp;   // Save to the handle cookie
            asyncHandle.Send();

**Comment by oliverw** [comment]
Thanks for the clarification.
