### ISSUE TITLE
System.AccessViolationException In StreamHandle.WriteStream

### ISSUE THREAD

**Issue by lth3726381** [StormHub/NetUV#58]
Same scene in #57 ,but sometimes the excetion is AccessViolationException.
System.AccessViolationException
HResult=0x80004003
Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  StackTrace:
>[manage to native]		
NetUV.Core.dll!NetUV.Core.Native.NativeMethods.WriteStream(System.IntPtr requestHandle = {System.IntPtr}, System.IntPtr streamHandle = {System.IntPtr}, ref NetUV.Core.Native.uv_buf_t[] bufs = {NetUV.Core.Native.uv_buf_t[1]}) line 122	
 	NetUV.Core.dll!NetUV.Core.Handles.StreamHandle.WriteStream(NetUV.Core.Requests.WriteRequest request = {NetUV.Core.Requests.WriteRequest}) line 215	
 	NetUV.Core.dll!NetUV.Core.Handles.Pipeline.QueueWrite(NetUV.Core.Native.BufferRef bufferRef = {System.Action<NetUV.Core.Handles.StreamHandle, System.Exception>}, System.Action<NetUV.Core.Handles.StreamHandle, System.Exception> completion = {NetUV.Core.Native.BufferRef}) line 135	
 	NetUV.Core.dll!NetUV.Core.Handles.StreamHandle.QueueWriteStream(byte[] array = {byte[3518]}, int offset = 0, int count = 3518, System.Action<NetUV.Core.Handles.StreamHandle, System.Exception> completion = {System.Action<NetUV.Core.Handles.StreamHandle, System.Exception>}) line 182	
 	UvTcpPacketServer.dll!ServerEngine.UvTcpPacketSession<RoomServer.ToClient.ToClientServer>.Send(byte[] bytes = {byte[3514]}, int offset = 0, int count = 3514) line 49	
 	CommandServer.dll!ServerEngine.CommandSession<RoomServer.ToClient.ToClientServer>.Send(CommandModel.ICommand command = {RoomServer.Commands.ViewUpdate}) line 24	
 	RoomServer.dll!RoomServer.Commands.ViewUpdate.OnExecute(RoomServer.ToClient.ToClientSession session = {RoomServer.ToClient.ToClientSession}) line 26	
 	CommandServer.dll!ServerEngine.CommandBase<RoomServer.ToClient.ToClientSession>.OnExecute(object session = {RoomServer.ToClient.ToClientSession}) line 37	
 	CommandServer.dll!ServerEngine.CommandServer<RoomServer.ToClient.ToClientSession>..ctor.AnonymousMethod__7_0() line 45	
 	System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)

**Comment by StormHub** [comment]
There are two possible references causing the exception, one is that the tcp handle itself was invalid, e.g. disposed or closed. Or the request has been disposed. From the stack trace, it looks like the byte array is ok, no violation in length.  
Are the writes actually called all in the loop thread?

**Comment by StormHub** [comment]
Please try to use
https://github.com/StormHub/NetUV/blob/dev/src/NetUV.Core/Channels/EventLoop.cs

**Comment by lth3726381** [comment]
writes are called from other threads,e.g .net's task thread pool

**Comment by StormHub** [comment]
#57 If you are running into issues, please let me know and I can deal with them in the EventLoop
